#Colocando o TextMate como editor do GIT
export GIT_EDITOR="mate -w"

#Comandos do RVM
if [[ -s $HOME/.rvm/scripts/rvm ]] ; then 
   source $HOME/.rvm/scripts/rvm
fi

# MacPorts Installer addition on 2011-04-10_at_23:23:46: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

#Customizacao do terminal segundo Nando Vieira
export GREP_OPTIONS="--color=auto"
export GREP_COLOR="4;33"
export CLICOLOR="auto"

alias ls="ls -G"

PATH=$PATH/Library/PostgreSQL/8.3/bin

#Colocando o encodding padrao para utf-8
export LC_CTYPE=en_US.UTF-8

#Svn do Collanb
export PATH=/opt/subversion/bin:$PATH

#Git
export PATH=$PATH:/usr/local/git/bin/

#resolvendo o bug do lion quanto ao imagicmagick
export MAGICK_HOME="/Users/thiagosampaio/Library/Imagemagic/ImageMagick-6.7.1"
export PATH="$MAGICK_HOME/bin:$PATH"
export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib/"
